FORMAT: 1A
HOST: localhost\apc

# amBX Peripheral Controller
A web-aware means to control a local instance of amBX Peripheral Controller (aPC) Server.

# Summary
The main usage of this API is to get the following:

* Information about the currently running scene(s)
* An indication of the supported integrated scenes
* The ability to push scenes

Both XML and JSON are supported - examples below target JSON.


# Group Integrated Scenes

## Integrated Scenes Collection [/integrated/]
Used to work collectively with all integrated scenes.

+ Model (application/json)

    + Body
    
            {
                [
                
                
                    {
                        "SceneName": "ccnet_red",
                        "IsEvent": false,
                        "IsSynchronised": false,
                        "SceneLength": 1000
                    },
                    {
                        "SceneName": "ccnet_green",
                        "IsEvent": false,
                        "IsSynchronised": false,
                        "SceneLength": 1000
                    }
                ]
            }
    

## Get details of all defined integrated scenes [GET]
+ Response 200 

    [Integrated Scenes Collection][]


## Integrated Scene [/integrated/{name}]
Used to manipulate specific integrated scenes.

+ Parameters
  + name (string) ... The name of the integrated scene

+ Model (application/json)

    The full details of the integrated scene.

    + Body

            {
                "IsExclusive": false,
                "SceneType": "Desync",
                "Frames": [
                    {
                        "Length": 1000,
                        "IsRepeated": false,
                        "Lights": {
                            "North": {
                                "Intensity": 1,
                                "Red": 1,
                                "Green": 0,
                                "Blue": 0
                            },
                            "NorthEast": {
                                "Intensity": 1,
                                "Red": 1,
                                "Green": 0,
                                "Blue": 0
                            },
                            "East": {
                                "Intensity": 1,
                                "Red": 1,
                                "Green": 0,
                                "Blue": 0
                            },
                            "SouthEast": {
                                "Intensity": 1,
                                "Red": 1,
                                "Green": 0,
                                "Blue": 0
                            },
                            "South": {
                                "Intensity": 1,
                                "Red": 1,
                                "Green": 0,
                                "Blue": 0
                            },
                            "SouthWest": {
                                "Intensity": 1,
                                "Red": 1,
                                "Green": 0,
                                "Blue": 0
                            },
                            "West": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "NorthWest": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "FadeTime": 500
                    },
                    "Fans": null,
                    "Rumbles": null
                    }
                ]
            }

## Get the definition of the scene [GET]
+ Request

        Accept: application/json


+ Response 200

    [Integrated Scene][]

+ Response 404

## Run the given scene [POST]
+ Response 200
+ Response 404


# Group Custom Scenes
Handling custom-built scenes

## Parse custom Scene [/custom/parse]
Confirm if a given custom scene is correctly formed.

## Parse given scene [POST]
+ Request (application/json)

        {
            "IsExclusive": false,
            "SceneType": "Desync",
            "Frames": [
                {
                    "Length": 1000,
                    "IsRepeated": false,
                    "Lights": {
                        "North": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "NorthEast": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "East": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "SouthEast": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "South": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                       },
                       "SouthWest": {
                           "Intensity": 1,
                           "Red": 1,
                           "Green": 0,
                           "Blue": 0
                       },
                       "West": {
                       "Intensity": 1,
                       "Red": 1,
                       "Green": 0,
                       "Blue": 0
                   },
                   "NorthWest": {
                       "Intensity": 1,
                       "Red": 1,
                       "Green": 0,
                       "Blue": 0
                   },
                   "FadeTime": 500
                },
                "Fans": null,
                "Rumbles": null
                }
            ]
        }

+ Response 200
+ Response 500



## Run custom Scene [/custom/run]
Confirm if a given custom scene is correctly formed

## Run given scene [POST]
+ Request (application/json)

        {
            "IsExclusive": false,
            "SceneType": "Desync",
            "Frames": [
                {
                    "Length": 1000,
                    "IsRepeated": false,
                    "Lights": {
                        "North": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "NorthEast": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "East": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "SouthEast": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                        },
                        "South": {
                            "Intensity": 1,
                            "Red": 1,
                            "Green": 0,
                            "Blue": 0
                       },
                       "SouthWest": {
                           "Intensity": 1,
                           "Red": 1,
                           "Green": 0,
                           "Blue": 0
                       },
                       "West": {
                       "Intensity": 1,
                       "Red": 1,
                       "Green": 0,
                       "Blue": 0
                   },
                   "NorthWest": {
                       "Intensity": 1,
                       "Red": 1,
                       "Green": 0,
                       "Blue": 0
                   },
                   "FadeTime": 500
                },
                "Fans": null,
                "Rumbles": null
                }
            ]
        }

+ Response 200
+ Response 500