using aPC.Client.Morse.Communication;
using aPC.Common.Client.Tests.Communication;
using aPC.Common.Defaults;
using aPC.Common.Entities;
using NUnit.Framework;
using System;

namespace aPC.Client.Morse.Tests.Communication
{
  [TestFixture]
  internal class NotificationClientTests
  {
    private NotificationClient client;
    private TestNotificationService host;

    [TestFixtureSetUp]
    public void SetupTests()
    {
      host = new TestNotificationService();
      client = new NotificationClient(host.Hostname);
    }

    [TestFixtureTearDown]
    public void FixtureTearDown()
    {
      host.Dispose();
    }

    [TearDown]
    public void TearDown()
    {
      host.Scenes.Clear();
    }

    [Test]
    public void PushingAnIntegratedScene_ThrowsException()
    {
      Assert.Throws<NotSupportedException>(() => client.PushSceneName("blah"));
    }

    [Test]
    public void PushingACustomScene_SendsTheExpectedScene()
    {
      var scene = new amBXScene();
      client.PushScene(scene);

      Assert.AreEqual(1, host.Scenes.Count);
      Assert.AreEqual(false, host.Scenes[0].Item1);
      Assert.AreEqual(scene, host.Scenes[0].Item2);
    }

    [Test]
    public void PushingACustomAmBXScene_SuccesfullySendsScene()
    {
      var scene = new DefaultScenes().Rainbow;

      client.PushScene(scene);

      Assert.AreEqual(1, host.Scenes.Count);
      Assert.AreEqual(false, host.Scenes[0].Item1);
      Assert.AreEqual(serialisedRainbow, host.Scenes[0].Item2);
    }

    private const string serialisedRainbow = @"<?xml version=""1.0"" encoding=""utf-16""?>
<amBXScene xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <IsExclusive>true</IsExclusive>
  <SceneType>Desync</SceneType>
  <Frames>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0</Green>
            <Blue>0</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>0.5</Green>
            <Blue>0</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>1</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>1</Green>
            <Blue>0</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.3</Red>
            <Green>0</Green>
            <Blue>0.5</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <LightSection>
        <Lights>
          <Light>
            <Direction>North</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>NorthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>East</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>SouthEast</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>South</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>SouthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>West</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
          <Light>
            <Direction>NorthWest</Direction>
            <FadeTime>100</FadeTime>
            <Red>0.56</Red>
            <Green>0</Green>
            <Blue>1</Blue>
          </Light>
        </Lights>
      </LightSection>
    </Frame>
  </Frames>
</amBXScene>";
  }
}