using aPC.Client.Morse.Communication;
using aPC.Common.Client.Tests.Communication;
using aPC.Common.Defaults;
using NUnit.Framework;
using System;

namespace aPC.Client.Morse.Tests.Communication
{
  [TestFixture]
  internal class NotificationClientTests
  {
    [TestFixtureSetUp]
    public void SetupTests()
    {
      mHost = new TestNotificationService();
      mClient = new NotificationClient(mHost.Hostname);
    }

    [TestFixtureTearDown]
    public void FixtureTearDown()
    {
      mHost.Dispose();
    }

    [TearDown]
    public void TearDown()
    {
      mHost.Scenes.Clear();
    }

    [Test]
    public void PushingAnIntegratedScene_ThrowsException()
    {
      Assert.Throws<NotSupportedException>(() => mClient.PushIntegratedScene("blah"));
    }

    [Test]
    public void PushingACustomScene_SendsTheExpectedScene()
    {
      mClient.PushCustomScene("scene");

      Assert.AreEqual(1, mHost.Scenes.Count);
      Assert.AreEqual(false, mHost.Scenes[0].Item1);
      Assert.AreEqual("scene", mHost.Scenes[0].Item2);
    }

    [Test]
    public void PushingACustomAmBXScene_SuccesfullySendsScene()
    {
      var lScene = new DefaultScenes().Rainbow;

      mClient.PushCustomScene(lScene);

      Assert.AreEqual(1, mHost.Scenes.Count);
      Assert.AreEqual(false, mHost.Scenes[0].Item1);
      Assert.AreEqual(mSerialisedRainbow, mHost.Scenes[0].Item2);
    }

    private NotificationClient mClient;
    private TestNotificationService mHost;

    private const string mSerialisedRainbow = @"<?xml version=""1.0"" encoding=""utf-16""?>
<amBXScene xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <IsExclusive>true</IsExclusive>
  <SceneType>Desync</SceneType>
  <Frames>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0</Green>
          <Blue>0</Blue>
        </NorthWest>
      </Lights>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>0.5</Green>
          <Blue>0</Blue>
        </NorthWest>
      </Lights>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>1</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </NorthWest>
      </Lights>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>1</Green>
          <Blue>0</Blue>
        </NorthWest>
      </Lights>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>0</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </NorthWest>
      </Lights>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>0.3</Red>
          <Green>0</Green>
          <Blue>0.5</Blue>
        </NorthWest>
      </Lights>
    </Frame>
    <Frame>
      <Length>1000</Length>
      <IsRepeated>true</IsRepeated>
      <Lights>
        <FadeTime>500</FadeTime>
        <North>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </North>
        <NorthEast>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </NorthEast>
        <East>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </East>
        <SouthEast>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </SouthEast>
        <South>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </South>
        <SouthWest>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </SouthWest>
        <West>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </West>
        <NorthWest>
          <Intensity>1</Intensity>
          <Red>0.56</Red>
          <Green>0</Green>
          <Blue>1</Blue>
        </NorthWest>
      </Lights>
    </Frame>
  </Frames>
</amBXScene>";
  }
}